name: ESP32 Build and Wokwi Simu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ESP-IDF firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3
          target: esp32
          path: .

      - name: Install Wokwi CLI
        run: |
          curl -L https://wokwi.com/ci/install.sh | sh
          echo "$HOME/.wokwi/bin" >> "$GITHUB_PATH"

      - name: Verify Wokwi firmware files
        run: |
          echo "========== BUILD FILES =========="
          ls -lh build/ESP32_LCD_I2C_IDF5.bin
          ls -lh build/ESP32_LCD_I2C_IDF5.elf
          ls -lh build/flasher_args.json
          echo "========== FLASHER ARGS =========="
          cat build/flasher_args.json
          echo "========== DIAGRAM =========="
          cat diagram.json
          echo "========== WOKWI CONFIG =========="
          cat wokwi.toml
          
      - name: Run Wokwi simulation
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run: |
          rm -f wokwi.log
    
          echo "========== START WOKWI =========="
    
          wokwi-cli . --timeout 10000  --serial-log-file wokwi.log
    
          EXIT_CODE=$?
    
          echo "========== WOKWI EXIT CODE =========="
          echo "$EXIT_CODE"
    
          echo "========== WOKWI LOG FILE =========="
          if [ -f wokwi.log ]; then
            wc -c wokwi.log
            cat wokwi.log
          else
            echo "ERROR: wokwi.log was not created"
          fi
    
          echo "========== END WOKWI =========="
    
          exit $EXIT_CODE

      - name: Show Wokwi serial log
        if: always()
        run: |
          echo "========== WOKWI SERIAL LOG =========="
          ls -l wokwi.log || true
          cat wokwi.log
          echo "========== END WOKWI SERIAL LOG =========="

      - name: Upload Wokwi log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wokwi-log
          path: wokwi.log
          if-no-files-found: ignore
